jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 35.226.250.22
    https:
      hosts:
        - prob140-staging.datahub.berkeley.edu