dependencies:
 - name: prometheus
   version: 11.11.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 5.5.5
   repository: https://kubernetes-charts.storage.googleapis.com
