nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/stat89a

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  auth:
    type: custom
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users
          # Professor
          - mahoneymw
          # GSIs
          - krinsman
          - theisen
          # UGSI
          - wqixuan

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/stat89a-user-image
    storage:
      static:
        pvcName: home-nfs
        subPath: "{username}"
      type: static
    defaultUrl: "/lab"
