
jupyterhub:
  proxy:
    service:
      loadBalancerIP: 34.67.27.111
    https:
      hosts:
        # FIXME: Make a DNS entry for the service IP first before uncommenting it
        - stat89a.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi