jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.66.75.97
    https:
      hosts:
        - stat89a-staging.datahub.berkeley.edu