nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/homedirs-other-2020-07-29/data102

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  auth:
    type: custom
    admin:
      users:
        # infrastructure
        - felder
        - rylo
        - yuvipanda
        # instructors
        - fernando.perez
        - michael_jordan
        # gsis
        #- placeholder

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
    memory:
      guarantee: 1G
      limit: 2G
    image:
      name: gcr.io/ucb-datahub-2018/data102-user-image
    defaultUrl: "/lab"
