jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.66.74.162
    https:
      hosts:
        - data102-staging.datahub.berkeley.edu
