jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    # service:
      # make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      # loadBalancerIP: <IP of {{cookiecutter.hub_name}}.datahub.berkeley.edu
    # uncomment once DNS entry has been made
    # https:
      # hosts:
        # - {{cookiecutter.hub_name}}-staging.datahub.berkeley.edu