nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/datahubhomes-2020-07-29/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    extraConfig:
      # 04, since in hub/values.yaml we explicitly set it to /home/jovyan as 03
      04-rstudio-home: |
        c.KubeSpawner.working_dir = '/home/rstudio'

  auth:
    type: custom # This enables canvas auth
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # PH250WF+PH250WG Instructors, issue 882
          - jadebc
          - jcolford
          # PH250WF+PH250WG student assistants, issue 882
          - anna-nguyen
          - lucascarlton
          - m.ruiz
          - nolanpokpongkiat
          - stephaniemholm
          - wmjilek
          # List of other admin users

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    storage:
      type: static
      homeMountPath: /home/rstudio
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
    defaultUrl: "/rstudio"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/r-user-image
    networkPolicy:
      enabled: true
      egress:
        # defaults
        - ports:
            - port: 53
              protocol: UDP
        - ports:
            - port: 80
              protocol: TCP
        - ports:
            - port: 443
              protocol: TCP
        # enabling ssh for private git repos
        - ports:
            - port: 22
              protocol: TCP
