jupyterhub:
  proxy:
    service:
      loadBalancerIP: 35.223.70.39
    https:
      hosts:
        - eecs.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 60
