nfsPVC:
  enabled: true
  nfs:
    serverIP: nfsserver-01
    shareName: export/datahubhomes-2020-07-29/homes

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  proxy:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
  auth:
    type: custom  # uses canvas auth, see hub/values.yaml
    admin:
      users:
          # infrastructure
          - rylo
          - yuvipanda
          - felder
          # List of other admin users

  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: gamma-pool
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: gcr.io/ucb-datahub-2018/julia-user-image
